services:
  ocg:
    container_name: ocg

    build: ./onlinecanvasgames
    env_file:
      - .env
    restart: always
    ports:
      - "${OCG_PORT}:${OCG_PORT}"
    depends_on:
      db:
        condition: service_healthy
      storage:
        condition: service_started
    command: ./main

  storage:
    container_name: storage
    
    build: ./storage
    env_file:
      - .env
    restart: always
    ports:
      - "${STORAGE_PORT}:${STORAGE_PORT}"
    volumes:
      - ./storage/storage/static:/app/storage/static
      - ./storage/storage/image:/app/storage/image
    command: ./main
  
  db:
    container_name: ocg_db

    env_file:
      - .env
    image: postgres
    restart: always
    volumes:
      - pgdbdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s
  
  adminer:
    container_name: adminer

    image: adminer
    restart: always
    ports:
      - ${ADMINER_PORT}:8080

volumes:
  pgdbdata: null
