services:
  ocg:
    container_name: ocg

    build: ./onlinecanvasgames
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
    command: ./main
  
  db:
    container_name: ocg_db

    image: postgres
    restart: always
    env_file:
      - .env
    volumes:
      - pgdbdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s
  
  adminer:
    container_name: adminer

    image: adminer
    restart: always
    ports:
      - 8081:8080
  
volumes:
  pgdbdata: null
