CREATE TABLE IF NOT EXISTS games (
    id SERIAL PRIMARY KEY,
    title VARCHAR(63) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS users (
    id SERIAL PRIMARY KEY,
    name VARCHAR(31) NOT NULL UNIQUE,
    hash VARCHAR(60) NOT NULL,
    date DATE DEFAULT CURRENT_DATE NOT NULL
);

INSERT INTO games (title) VALUES ('clicker') ON CONFLICT (title) DO NOTHING;
INSERT INTO games (title) VALUES ('platformer') ON CONFLICT (title) DO NOTHING;